version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"     # HTTP
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    networks:
      - shared      # Rețeaua shared pentru toate serviciile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: brain_test_db,car_general_db,ohmydoc_db
      PMA_PORTS: 3306,3307,3308 # Specifică porturile dacă sunt diferite
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80" # Accesibil la acest port
    networks:
      - shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.test`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  shared:
    external: true
